# Generated by Django 6.0.5 on 2026-05-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campanha', models.CharField(default='Rifa Beneficente', max_length=200)),
                ('subtitulo', models.CharField(default='Campanha de Reforma do Templo', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('data_sorteio', models.DateField(blank=True, null=True)),
                ('premio', models.CharField(default='Cesta Especial', max_length=200)),
                ('causa', models.CharField(default='Reforma do Templo', max_length=200)),
                ('pix_chave', models.CharField(default='contato@igrejaesperanca.com', max_length=200)),
                ('total_numeros', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Configuração',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vencedor', models.IntegerField()),
                ('nome_vencedor', models.CharField(max_length=100)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sorteio',
                'ordering': ['-realizado_em'],
            },
        ),
    ]
