# Generated by Django 6.0.5 on 2026-05-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='pix_emv',
            field=models.TextField(blank=True, help_text='Cole aqui o código EMV completo (copia e cola do banco). Se preenchido, o QR Code usa ele. Se vazio, usa a chave PIX acima.'),
        ),
    ]
