# Generated by Django 5.2.7 on 2026-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0002_configuracao_pix_emv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transacao', models.CharField(max_length=200, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comprovante Usado',
            },
        ),
    ]
