# Generated by Django 5.2.7 on 2026-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0003_comprovanteusado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('nome_pagador', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_hora', models.CharField(blank=True, max_length=100)),
                ('id_transacao', models.CharField(blank=True, max_length=300)),
                ('suspeito', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
