# Generated by Django 5.2.7 on 2026-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0004_comprovanteanalise'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroComprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(blank=True, max_length=100)),
                ('pagador', models.CharField(blank=True, max_length=200)),
                ('data_hora_pix', models.CharField(blank=True, max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('texto_ocr', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Comprovante',
                'verbose_name_plural': 'Registros de Comprovantes',
            },
        ),
        migrations.DeleteModel(
            name='ComprovanteAnalise',
        ),
        migrations.DeleteModel(
            name='ComprovanteUsado',
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='pix_emv',
            field=models.TextField(blank=True),
        ),
    ]
