# Generated by Django 5.2.7 on 2026-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0005_registrocomprovante_delete_comprovanteanalise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprovante',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
