# Generated by Django 5.2.7 on 2026-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0006_registrocomprovante_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprovante',
            name='assinatura_transacao',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registrocomprovante',
            name='hash_imagem',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registrocomprovante',
            name='id_transacao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrocomprovante',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
