# Generated by Django 5.2.7 on 2026-06-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0007_registrocomprovante_assinatura_transacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transacao', models.CharField(blank=True, max_length=200)),
                ('hash_imagem', models.CharField(blank=True, max_length=64)),
                ('assinatura', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comprovante Usado',
            },
        ),
        migrations.RemoveField(
            model_name='registrocomprovante',
            name='assinatura_transacao',
        ),
        migrations.RemoveField(
            model_name='registrocomprovante',
            name='hash_imagem',
        ),
        migrations.RemoveField(
            model_name='registrocomprovante',
            name='id_transacao',
        ),
    ]
