# Generated by Django 5.2.7 on 2026-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0008_comprovanteusado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='comprovantes/')),
                ('hash_imagem', models.CharField(max_length=64, unique=True)),
                ('assinatura', models.CharField(max_length=255, unique=True)),
                ('pagador', models.CharField(max_length=100)),
                ('data_hora', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
