# Generated by Django 5.2.7 on 2026-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0009_comprovante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprovanteusado',
            options={'verbose_name': 'Comprovante Usado', 'verbose_name_plural': 'Comprovantes Usados'},
        ),
        migrations.AddField(
            model_name='comprovanteusado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
