# Generated by Django 5.2.7 on 2026-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0010_alter_comprovanteusado_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprovante',
        ),
        migrations.DeleteModel(
            name='ComprovanteUsado',
        ),
        migrations.RemoveField(
            model_name='registrocomprovante',
            name='numero',
        ),
        migrations.AddField(
            model_name='registrocomprovante',
            name='assinatura',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='registrocomprovante',
            name='hash_imagem',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
