# Generated by Django 5.2.7 on 2026-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0011_delete_comprovante_delete_comprovanteusado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprovante',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocomprovante',
            name='assinatura',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
