# Generated by Django 5.2.7 on 2026-06-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0012_registrocomprovante_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaComprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('aprovado', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='tentativas/')),
                ('texto_ocr', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tentativa de Comprovante',
                'ordering': ['-data_hora'],
            },
        ),
    ]
