# Generated by Django 5.2.7 on 2026-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0013_tentativacomprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('reservado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número Reservado',
            },
        ),
    ]
